/**
 * Add synonyms for icons to this file to help users find them on the website.
 *
 * The format is
 *   icon: ['synonym one', 'synonym two']
 */

module.exports = {
  activity: ['window'],
  'add-circle': ['plus', 'create', 'new'],
  'add-item': ['plus', 'create', 'new'],
  add: ['plus', 'create', 'new'],
  addon: [],
  'app-switcher': [],
  'arrow-down': [],
  'arrow-left-circle': ['back', 'previous'],
  'arrow-left': ['back', 'previous'],
  'arrow-right-long': ['forward', 'next'],
  'arrow-right': ['forward', 'next'],
  'arrow-up': [],
  atlassian: ['charlie'],
  attachment: ['paperclip'],
  'audio-circle': ['music', 'note', 'sound'],
  audio: ['music', 'note', 'sound'],
  backlog: [],
  billing: ['invoice', 'receipt'],
  bitbucket: [],
  'bitbucket/branches': [],
  'bitbucket/builds': [],
  'bitbucket/clone': [],
  'bitbucket/commits': [],
  'bitbucket/compare': [],
  'bitbucket/forks': [],
  'bitbucket/output': [],
  'bitbucket/pipelines': [],
  'bitbucket/pullrequests': [],
  'bitbucket/repos': [],
  'bitbucket/snippets': ['scissors'],
  board: [],
  book: [],
  'bullet-list': ['ul'],
  'calendar-filled': ['date'],
  calendar: ['date'],
  'camera-filled': ['photo'],
  'camera-rotate': ['photo'],
  'camera-take-picture': ['photo'],
  camera: ['photo'],
  cancel: ['cross', 'x', 'close'],
  canvas: ['easel'],
  'check-circle': ['tick'],
  check: ['tick'],
  checkbox: ['tick'],
  'chevron-down-circle': [],
  'chevron-down': [],
  'chevron-left-circle': ['back', 'previous'],
  'chevron-left': ['back', 'previous'],
  'chevron-right-circle': ['forward', 'next'],
  'chevron-right': ['forward', 'next'],
  'chevron-up-circle': [],
  'chevron-up': [],
  code: ['source'],
  comment: ['chat', 'speech'],
  component: ['block', 'lego'],
  confirm: ['tick', 'check'],
  confluence: [],
  copy: ['duplicate'],
  'cross-circle': ['close', 'x', 'cancel'],
  cross: ['close', 'x', 'cancel'],
  dashboard: ['window', 'grid'],
  decision: [],
  'detail-view': [],
  'discover-filled': ['compass', 'navigate'],
  discover: ['compass', 'navigate'],
  'document-filled': ['page', 'paper', 'sheet', 'file'],
  document: ['page', 'paper', 'sheet', 'file'],
  documents: ['page', 'paper', 'sheet', 'file'],
  download: ['cloud'],
  dropbox: [],
  'edit-filled': ['pencil', 'write'],
  edit: ['pencil', 'write'],
  'editor/add': ['plus', 'create', 'new'],
  'editor/addon': ['jigsaw'],
  'editor/advanced': ['strikethrough', 'type', 'font', 'typography'],
  'editor/align-center': [],
  'editor/align-left': [],
  'editor/align-right': [],
  'editor/attachment': ['paperclip'],
  'editor/bold': [],
  'editor/bullet-list': ['ul'],
  'editor/close': ['x', 'cancel', 'cross'],
  'editor/code': ['source'],
  'editor/date': ['calendar'],
  'editor/decision': [],
  'editor/done': ['check', 'tick'],
  'editor/edit': ['pencil', 'write'],
  'editor/emoji': ['emoticon', 'smiley'],
  'editor/error': ['warning', 'alert'],
  'editor/expand': ['chevron', 'down'],
  'editor/feedback': ['announce', 'speaker', 'megaphone'],
  'editor/file': ['page', 'document', 'paper', 'sheet'],
  'editor/help': ['question'],
  'editor/hint': ['light', 'idea'],
  'editor/image-border': ['marquee', 'box'],
  'editor/image-resize': ['expand'],
  'editor/image': ['photo', 'picture'],
  'editor/indent': ['tab', 'spacing', 'padding'],
  'editor/info': [],
  'editor/italic': [],
  'editor/link': [],
  'editor/mention': ['@', 'person', 'user'],
  'editor/more': ['dots', 'ellipses'],
  'editor/note': ['document', 'page'],
  'editor/number-list': ['ol'],
  'editor/open': [],
  'editor/outdent': ['indent', 'tab', 'spacing', 'padding'],
  'editor/panel': ['info'],
  'editor/photo': ['camera'],
  'editor/recent': ['clock', 'time'],
  'editor/redo': [],
  'editor/remove': ['bin', 'trash', 'recycle', 'delete'],
  'editor/search': ['magnifying', 'glass', 'find'],
  'editor/table': ['grid'],
  'editor/task': ['checkbox', 'tick'],
  'editor/text-color': ['font'],
  'editor/underline': ['font', 'text'],
  'editor/undo': [],
  'editor/unlink': [],
  'editor/warning': ['alert', 'error'],
  emoji: ['emoticon', 'smiley'],
  'emoji/activity': ['tennis', 'ball'],
  'emoji/atlassian': [],
  'emoji/custom': ['plus', 'add', 'create', 'new'],
  'emoji/emoji': ['emoticon', 'smiley'],
  'emoji/flags': [],
  'emoji/food': [],
  'emoji/frequent': ['time', 'clock'],
  'emoji/nature': ['tree'],
  'emoji/objects': ['light'],
  'emoji/people': ['smiley', 'face'],
  'emoji/symbols': ['heart', 'love'],
  'emoji/travel': ['train', 'transport'],
  error: ['warning', 'alert'],
  expand: [],
  export: ['upload'],
  feedback: ['announce', 'speaker', 'megaphone'],
  file: ['document', 'paper', 'page', 'sheet'],
  filter: [],
  'folder-filled': ['directory'],
  folder: ['directory'],
  followers: ['person', 'user'],
  following: ['person', 'user'],
  googledrive: [],
  'graph-bar': ['chart', 'growth', 'data', 'statistics', 'analytics'],
  'graph-line': ['chart', 'growth', 'data', 'statistics', 'analytics'],
  help: ['question'],
  hint: ['idea', 'lightbulb'],
  hipchat: [],
  'hipchat/chevron-double-down': [],
  'hipchat/chevron-double-up': [],
  'hipchat/chevron-down': [],
  'hipchat/chevron-up': [],
  'hipchat/lobby': ['bell'],
  'hipchat/media-attachment-count': ['dot'],
  'hipchat/media-uploader': ['cloud'],
  'home-circle': [],
  'home-filled': [],
  'image-border': ['marquee', 'box'],
  'image-resize': ['expand'],
  image: ['picture', 'photo'],
  info: [],
  'invite-team': ['add', 'person', 'user'],
  'issue-raise': ['add', 'create', 'plus', 'new'],
  issue: ['tick', 'check', 'confirm', 'task'],
  issues: ['tick', 'check', 'confirm', 'task'],
  jira: [],
  'lightbulb-filled': ['idea'],
  lightbulb: ['idea'],
  'link-filled': [],
  link: [],
  list: ['justify', 'ul'],
  location: ['pin', 'gps', 'map'],
  'lock-circle': ['private', 'restricted', 'secure'],
  'lock-filled': ['private', 'restricted', 'secure'],
  lock: ['private', 'restricted', 'secure'],
  'log-in': ['sign'],
  marketplace: ['store', 'shop'],
  'media-services/actual-size': [],
  'media-services/add-comment': ['chat', 'new', 'create'],
  'media-services/arrow': [],
  'media-services/audio': ['music', 'note', 'sound'],
  'media-services/blur': ['pixelate'],
  'media-services/brush': ['paint'],
  'media-services/code': ['source'],
  'media-services/document': ['text'],
  'media-services/filter': [],
  'media-services/grid': ['table'],
  'media-services/image': ['photo', 'picture'],
  'media-services/line': [],
  'media-services/open-mediaviewer': [],
  'media-services/oval': ['ellipse'],
  'media-services/pdf': ['document'],
  'media-services/preselected': ['circle'],
  'media-services/presentation': ['chart', 'graph'],
  'media-services/scale-large': ['photo', 'picture', 'image'],
  'media-services/scale-small': ['photo', 'picture', 'image'],
  'media-services/spreadsheet': ['document', 'excel', 'sheets', 'table'],
  'media-services/square': ['rectangle', 'box'],
  'media-services/text': ['type', 'typography', 'font'],
  'media-services/unknown': ['document', 'file'],
  'media-services/video': ['film', 'camera'],
  'media-services/zip': ['compress'],
  'media-services/zoom-in': ['magnify'],
  'media-services/zoom-out': ['magnify'],
  mention: ['user', 'person', '@'],
  menu: ['hamburger', 'navigation'],
  'more-vertical': ['dots'],
  more: ['dots', 'ellipses'],
  'notification-all': ['bell', 'alarm'],
  'notification-direct': ['bell', 'alarm'],
  notification: ['bell', 'alarm'],
  'office-building': [],
  open: [],
  overview: [],
  'page-filled': ['file', 'document'],
  page: ['file', 'document'],
  pdf: ['document', 'file'],
  'people-group': ['person', 'user', 'group'],
  people: ['person', 'user', 'group'],
  person: ['person', 'user', 'avatar'],
  portfolio: [],
  preferences: ['settings', 'configuration', 'options'],
  'presence-active': ['dot'],
  'presence-busy': ['block', 'do not disturb'],
  'presence-unavailable': [],
  'question-circle': ['help'],
  question: ['help'],
  queues: [],
  quote: [],
  radio: [],
  recent: ['time', 'clock'],
  redo: [],
  refresh: ['cycle'],
  remove: ['bin', 'trash', 'delete', 'recycle'],
  'room-menu': [],
  'schedule-add': ['calendar', 'date', 'new'],
  'schedule-filled': ['calendar', 'date', 'new'],
  screen: ['desktop', 'computer', 'monitor'],
  search: ['find', 'magnify'],
  send: ['mail'],
  settings: ['cog', 'options', 'configuration'],
  share: [],
  ship: [],
  shortcut: ['export'],
  'sign-in': ['log'],
  'sign-out': ['log'],
  'star-filled': [],
  star: [],
  switcher: [],
  table: ['grid'],
  task: ['check', 'tick'],
  time: ['clock'],
  trash: ['bin', 'remove', 'delete', 'recycle'],
  tray: ['inbox'],
  undo: [],
  unlink: [],
  'unlock-circle': [],
  upload: ['cloud'],
  'user-avatar-circle': ['person'],
  'vid-audio-muted': ['microphone', 'sound'],
  'vid-audio-on': ['microphone', 'sound'],
  'vid-backward': ['rewind'],
  'vid-camera-off': ['video'],
  'vid-connection-circle': ['signal', 'bar'],
  'vid-forward': ['fast'],
  'vid-full-screen-off': ['collapse', 'close'],
  'vid-full-screen-on': ['expand'],
  'vid-hang-up': ['end', 'call'],
  'vid-hd-circle': ['high', 'definition'],
  'vid-pause': [],
  'vid-play': [],
  'vid-raised-hand': ['person', 'question', 'user', 'arm'],
  'vid-share-screen': [],
  'vid-speaking-circle': ['sound', 'talk', 'audio'],
  'video-circle': ['video', 'camera'],
  'video-filled': ['video', 'camera'],
  warning: ['error', 'alert'],
  'watch-filled': ['visible', 'visibility', 'eye'],
  watch: ['visible', 'visibility', 'eye'],
  world: ['globe', 'earth'],
};
