import {
  akColorN800,
  akColorN20,
  akColorN30,
  akColorN90,
  akColorN400,
  akColorG400,
  akColorP300,
  akColorY300,
  akColorT300,
  akColorT500,
  akColorB500,
} from '@atlaskit/util-shared-styles';

import { Theme } from './themeBuilder';

export const defaultColors: Theme = {
  lineNumberColor: akColorN90,
  lineNumberBgColor: akColorN30,
  backgroundColor: akColorN20,
  textColor: akColorN800,
  substringColor: akColorN400,
  keywordColor: akColorB500,
  attributeColor: akColorT500,
  selectorTagColor: akColorB500,
  docTagColor: akColorY300,
  nameColor: akColorB500,
  builtInColor: akColorB500,
  literalColor: akColorB500,
  bulletColor: akColorB500,
  codeColor: akColorB500,
  additionColor: akColorB500,
  regexpColor: akColorT300,
  symbolColor: akColorT300,
  variableColor: akColorT300,
  templateVariableColor: akColorT300,
  linkColor: akColorP300,
  selectorAttributeColor: akColorT300,
  selectorPseudoColor: akColorT300,
  typeColor: akColorT500,
  stringColor: akColorG400,
  selectorIdColor: akColorT500,
  selectorClassColor: akColorT500,
  quoteColor: akColorT500,
  templateTagColor: akColorT500,
  deletionColor: akColorT500,
  titleColor: akColorP300,
  sectionColor: akColorP300,
  commentColor: akColorN400,
  metaKeywordColor: akColorG400,
  metaColor: akColorN400,
  functionColor: akColorN800,
  numberColor: akColorB500
};
